services:
  backend:
    # Use existing image with auto-reload enabled
    image: web-content-analyzer-backend:chromadb
    container_name: web-content-analyzer-backend-dev
    env_file:
      - .env
    environment:
      - SERVICE=api
      - PYTHONPATH=/app/backend
      - RELOAD=true
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for live reload
      - ./backend:/app/backend:cached
      - ./data:/app/data:cached
    networks:
      - web-content-analyzer-network
    restart: unless-stopped
    # Override the CMD to enable auto-reload
    command: >
      sh -c "cd /app/backend && 
             python -m uvicorn api.main:app 
             --host 0.0.0.0 
             --port 8000 
             --reload 
             --reload-dir /app/backend"

  frontend:
    # Use existing image with auto-reload enabled
    image: web-content-analyzer-frontend:fixed-streamlit-config
    container_name: web-content-analyzer-frontend-dev
    env_file:
      - .env
    environment:
      - SERVICE=frontend
      - PYTHONPATH=/app/frontend
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=auto
    ports:
      - "8501:8501"
    volumes:
      # Mount source code for live reload
      - ./frontend:/app/frontend:cached
      - ./data:/app/data:cached
    depends_on:
      - backend
    networks:
      - web-content-analyzer-network
    restart: unless-stopped

networks:
  web-content-analyzer-network:
    driver: bridge

volumes:
  data:
    driver: local
