version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-content-analyzer-backend
    container_name: web-content-analyzer-backend
    env_file:
      - .env.docker
    environment:
      - SERVICE=api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
      - ./src:/app/src
    networks:
      - web-content-analyzer-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-content-analyzer-frontend
    container_name: web-content-analyzer-frontend
    env_file:
      - .env.docker
    environment:
      - SERVICE=frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - web-content-analyzer-network
    restart: unless-stopped

networks:
  web-content-analyzer-network:
    driver: bridge

volumes:
  data:
    driver: local
